name: Update Weather Data

on:
  schedule:
    - cron: '39 13 * * *'  # Setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Memungkinkan untuk dijalankan secara manual

jobs:
  update-weather-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install joblib requests pandas

    - name: Run Weather Data Prediction and Update JSON
      run: |
        python test_Prediksi.py  # Skrip Python Anda yang memperbarui file JSON

    - name: Commit Updated JSON
      run: |
        git config --global user.name "PlaneFly545"
        git config --global user.email "prabawasandi545@gmail.com"
        git add weather_prediction.json
        git commit -m "Update weather prediction data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
